//
// Created by freek on 12/02/19.
//

#ifndef TECHNICAL_CHALLENGE_2019_SETTINGS_H
#define TECHNICAL_CHALLENGE_2019_SETTINGS_H

namespace Settings {
    int MORPHOLOGICAL_OPENING_SIZE = 10;
    int DERIVATIVE_BUFFER_SIZE = 4;
    int IMAGE_WIDTH = 640;
    int IMAGE_HEIGHT = 480;
    bool COMPLICATED_DIFFERENCE_CALCULATION = false;
    bool ENABLE_DRAWING = true;
};

#endif //TECHNICAL_CHALLENGE_2019_SETTINGS_H
